### ISSUE TITLE
Investigate complex state types

### ISSUE THREAD

**Issue by abalfour** [psibr/REstate-Legacy#14]
Current proposed complex types include:

- Service States (is ACK optional?)
- Broadcast (do we need to provide ACK capability?)
- Delay (as related to ChronoTriggers)

**Comment by aidapsibr** [comment]
One example of a Service State with auto-retry and ACK enforcement.

![servicestate](https://cloud.githubusercontent.com/assets/621605/20212758/cbbdfa8c-a7b9-11e6-9a4b-eb59258ee6ce.png)

**Comment by aidapsibr** [comment]
This was resolved in 6b9ee7ab45af72d9624ab3e09b98128d41173ee8
