### ISSUE TITLE
In-Memory repository (Scheduler) need to exist for tests.

### ISSUE THREAD

**Issue by aidapsibr** [psibr/REstate-Legacy#7]
As a SDET, I need in-memory repositories to unit test most components efficiently.

Acceptance Criteria:
An In-Memory repository and factory exists for the Scheduler.
Each method is implemented.
Each method is covered in at least one unit test.

**Comment by aidapsibr** [comment]
Dependent on #10

**Comment by psibernetic** [comment]
Combining this with #9 as a unified domain.
